Update elFinder.class.php
fixed: 
try to delete a file if deleting files are not allowed, get the following message:
Fatal error: Undefined class constant 'ERROR_ACCESS_DENIED' in **\php\elFinderVolumeDriver.class.php on line 1748

additional changes in elFinderVolumeDriver.class.php